### ISSUE TITLE
Question: Self-service multitenancy?

### ISSUE THREAD

**Issue by xhejtman** [fluxcd/flux2-multi-tenancy#101]
Is it possible to use fluxcd in the following scenario:

1. cluster admin deploys fluxcd operator with appropriate settings
2. user can create gitrepo object referencing any git repository on gitlab/github to setup CI/CD to namespace that he controls without asking the admin to pre-setup the namespace, i.e., for many users, it can be on self-service basis.

From docs, I think it is not possible as there seems to be a need for admin to setup namespace in advance. Is that so?

**Comment by stefanprodan** [comment]
> From docs, I think it is not possible as there seems to be a need for admin to setup namespace in advance. Is that so?

Yes, onboarding tenants is a process that can be automated outside of Flux. For example, both Azure and Weaveworks offer this in their Flux Enterprise offerings.
