### ISSUE TITLE
How to best use a substitueFrom for information another namespace?

### ISSUE THREAD

**Issue by cquinn-dcsg** [fluxcd/flux2-multi-tenancy#118]
Hi,
I am trying to use the substituteFrom, however I need to use it from another namespace but do not want to allow cross namespace access.  I am trying to ensure that the ingresses in each cluster have the correct service FQDN.  The problem that I am running into is that I have multiple gitrepos going to different namespaces and I cannot seem to use the substituteFrom from another namespace.   It has been suggested to simply copy the configmap with the cluster variables to each namespace that needs it, however this does not seem to be a good solution because if anything changes, you then have a synchronization issue on the configmaps.  Any advice would be appreciated.

**Comment by kingdonb** [comment]
There are a number of tools you can use to sync secrets between namespaces, I'd probably recommend Kyverno first or maybe external-secrets operator. There's a project called `kubed` that is now `config-syncer` that might help. There are a few more things that come up when searching for "sync secrets Kubernetes" - this is probably the most helpful page of all from cert-manager:

https://cert-manager.io/docs/devops-tips/syncing-secrets-across-namespaces/

Also see Kyverno's doc:

https://kyverno.io/policies/other/s-z/sync-secrets/sync-secrets/

Flux is not opinionated about which of these tools you use. It's definitely a good idea not to copy the secret and make multiple copies that will all need to be manually kept up to date. You should load the secret multiple times from an external source, or copy it using a policy directive like Kyverno can let you do. But Flux will not allow cross-namespace references for secrets or configmaps, except in narrow cases (not this case anyway)

Flux actually recommends disabling cross-namespace references globally for multi-tenancy, which can be even less permissive than the default behavior, (at least if you have image update controller installed, so not technically default):

https://fluxcd.io/flux/installation/configuration/multitenancy/#how-to-configure-flux-multi-tenancy

**Comment by cquinn-dcsg** [comment]
Thank you for that information.
