### ISSUE TITLE
Question: Where does the gotk-components.yaml file go?

### ISSUE THREAD

**Issue by jonaskello** [fluxcd/flux2-multi-tenancy#12]
I bootstrapped a fleet-infra repo using the guide and then I went on to examine this example for multi-tenancy. I guess the fleet-infra in the bootstrapping guide is the same as the "platform admin repository" referenced there? The bootstrapping created files to install the CRD and controllers for flux in `flux-system/gotk-components.yaml` and `flux-system/gotk-sync.yaml`. However this example repo seems to not have these files at all. So I'm a bit confused, should these files still be in the "platform admin repository"?

**Comment by stefanprodan** [comment]
See https://github.com/fluxcd/flux2-multi-tenancy#bootstrap-the-staging-cluster

**Comment by jonaskello** [comment]
Thanks! I think I get it. So the flux-system files from the bootstrapping should go in the "platform admin repository", however those files are missing from this example since this repo represents the state before running `flux bootstrap`?

**Comment by stefanprodan** [comment]
> this repo represents the state before running flux bootstrap?

Yes, you need to fork it then run bootstrap as described in the readme:

> Install the Flux CLI and **fork this repository** on your personal GitHub account and export your GitHub access token, username and repo name.

**Comment by jonaskello** [comment]
Yes, got it now 👍  I was not following the instructions directly but instead trying to re-work a fleet-infra repo I already had bootstrapped some weeks ago into a multi-tenant repo. So what I was doing was looking at the file layout in this example and trying to refactor my existing repo into the same layout. I think that is why I got confused :-).
