### ISSUE TITLE
Question: Common Infrastructure Pattern?

### ISSUE THREAD

**Issue by MattMencel** [fluxcd/flux2-multi-tenancy#17]
I'm working of the great example here for multi-tenant. Wondered if there's a way to source a common `infrastructure.yaml` for all clusters, and then each individual cluster folder would include that common file and than any specific differences.

Hopefully my diagram here explains it a bit better.

```
/clusters
  /foo
    infra-foo.yaml
    infrastructure.yaml  //refers to the file in /clusters/common
  /bar
    infra-bar.yaml
    infrastructure.yaml  //refers to the file in /clusters/common
  /common
    infrastructure.yaml //common set of infrastructure references.
```

I'm looking for a way to avoid repeating infrastructure.yaml in a dozen plus different cluster folders. Hopefully just having to modify one infrastructure.yaml file and not multiple each time I add/update/delete an infrastructure component.

**Comment by MattMencel** [comment]
I realized I can just use kustomizations to source from a common infrastructure directory.

```
/clusters
  /foo
    foo-infra-patch.yaml // patches to common infrastructure
    kustomization.yaml  //refers to the kustomization in /clusters/common

  /common
    kustomization.yaml
    infrastructure.yaml //common set of infrastructure references.
 ```

**Comment by stefanprodan** [comment]
@MattMencel Kustomize overlays are super flexible, you can restructure the infra items to reduce repetition if the all workloads are configured the same for all clusters.
