### ISSUE TITLE
Tenant RBAC allows privilege escalation

### ISSUE THREAD

**Issue by jacekn** [fluxcd/flux2-multi-tenancy#20]
Example in this repo will create service accounts in the tenant namespaces and then grant `cluster-admin` role to them (namespace scoped).

This allows any user with enough privileges to read secrets or launch pods to escalate privileges up to the `cluster-admin` inside the namespace. Escalation workflow is:
1. Launch pod with `spec.serviceAccountName: dev-team`
2. Dump ServiceAccount token: `kubectl -ti podname -- cat /run/secrets/kubernetes.io/serviceaccount/token`
3. Users who have read-only access to secrets can read the token directly from the secret: `kubectl get secret dev-team-token-xxxxxxx`
4. Use the token to perform cluster-level perms within the namespace:
```
kubectl config set-credentials dev-team --token=$TOKEN
kubectl config set-context --current --user=dev-team
kubectl delete $restricted_resource
```

**Comment by stefanprodan** [comment]
> This allows any user with enough privileges to read secrets or launch pods

Yes, this is NOT privileged escalation, it’s the intended behavior. As documented in the readme, tenants have full control over their namespaces.

**Comment by jacekn** [comment]
> > This allows any user with enough privileges to read secrets or launch pods
> 
> Yes, this is NOT privileged escalation, it’s the intended behavior. As documented in the readme, tenants have full control over their namespaces.

Thank you for looking into this!
I understand that flux2, by design, does not allow for granular access control within namespaces. I'm not talking about "tenants" in flux2 sense here. _any_ user in the cluster, even if not created or maintained by flux, is able to elevate their privileges, provided they have enough access _read_ the secrets.
Another way to describe the security implication of the design is that it makes it impossible to have a user account with read only access to secrets in any namespace where flux is configured.
A big problem, from security perspective, is that it's not obvious that the escalation path exists - it's hidden in service accounts and flux2-multi-tenancy docs and it's very likely that operators will not be aware of this (in larger organization it's even possible that people writing RBAC rules are not aware flux2 is in use at all)

If there is no intention to lock permissions down would you accept a PR making the security implications much more explicit?

**Comment by stefanprodan** [comment]
> any user in the cluster, even if not created or maintained by flux, is able to elevate their privileges, provided they have enough access read the secrets.

The idea of GitOps implies that operations are driven with PR against the fleet and tenants repos and users (except for cluster admins) don't have direct access to the cluster, but only to their repos.

> If there is no intention to lock permissions down would you accept a PR making the security implications much more explicit?

Sure
