### ISSUE TITLE
Can platform admin and tenants share a single branch in a mono repo?

### ISSUE THREAD

**Issue by beyondbill** [fluxcd/flux2-multi-tenancy#21]
Besides finer management of Github permissions, what are the benefits of separating platform admin and each tenant as individual repos?

If Github permission is not a big concern for some users/orgs, it seems the current multi-repo pattern can be consolidated into a mono repo with the following structure.

```
├── admin
    ├── clusters
    │   ├── production
    │   └── staging
    ├── infrastructure
    │   ├── kyverno
    │   └── kyverno-policies
    └── tenants
        ├── base
        ├── production
        └── staging
├── tenants
    ├── dev-team
        ├── base
        │   ├── kustomization.yaml
        │   ├── podinfo-release.yaml
        │   └── podinfo-repository.yaml
        ├── production
        │   ├── kustomization.yaml
        │   └── podinfo-values.yaml
        └── staging
            ├── kustomization.yaml
            └── podinfo-values.yaml
```

Instead of adding every tenant repo as a GitSource, now we only need to add the mono-repo as a GitSource for all tenants. The difference for each tenant is the path. In details, 

```
flux create source git mono \
    --namespace=apps \
    --url=https://github.com/<org>/flux2-mono \
    --branch=main \
    --export > ./admin/tenants/base/sync.yaml

flux create kustomization dev-team \
    --namespace=apps \
    --service-account=dev-team \
    --source=GitRepository/mono \
    --export > ./admin/tenants/base/dev-team/sync.yaml

cd ./admin/tenants/base/dev-team/ && kustomize create --autodetect

cat << EOF | tee ./admin/tenants/staging/dev-team-patch.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dev-team
  namespace: apps
spec:
  path: ./tenants/dev-team/staging
EOF

cat << EOF | tee ./admin/tenants/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/dev-team
  - ../base/sync.yaml
patchesStrategicMerge:
  - dev-team-patch.yaml
EOF
```

The rest of instructions on multi-repo pattern should mostly still hold.

What do you think of this alternative repo pattern?

**Comment by stefanprodan** [comment]
> If Github permission is not a big concern for some users/orgs, it seems the current multi-repo pattern can be consolidated into a mono repo

Yes that's a good alternative if the tenants are part of the same organisation and changes to the main brach (cluster state) are done with PR where cluster admins are involved in the review process. If you allow tenants to push directly to the main branch, then they could easily disable the policies and gain full controller over the clusters.
