### ISSUE TITLE
Question: How to get SSH public key used for source

### ISSUE THREAD

**Issue by Nonymus** [fluxcd/flux2-multi-tenancy#3]
Hi, I'm trying to follow the example using internal git repositories.

I'm currently stuck with the source created by
```flux create source git dev-team \
    --namespace=apps \
    --url=https://github.com/<org>/<dev-team> \
    --branch=main \
    --export > ./tenants/base/dev-team/sync.yaml
```

Is there a way the query the SSH pubkey the source-controller will use to query the source, something like `fluxctl identity` in v1? Or do I have to provide my own key when using an internal git server?

Thanks for all the work, really like the project.

**Comment by stefanprodan** [comment]
Please see: https://github.com/fluxcd/flux2-multi-tenancy#onboard-tenants-with-private-repositories

**Comment by Nonymus** [comment]
Thanks. What confused me was that the objects created by `flux create ...` and a subsequent `flux export ...` are different from a one-step `flux create ... --export`, at least for repositories. I understand the reasoning, to protect secrets form ending up in plain in git, but it wasn't immediately obvious to me.
