### ISSUE TITLE
One team with multiple namespaces access

### ISSUE THREAD

**Issue by nuriel77** [fluxcd/flux2-multi-tenancy#31]
The examples show one team with one namespace `apps`.
What would be the best practice to allow team `dev-team` permissions in multiple namespaces?
Would it be a good approach to have one ServiceAccount for the team and give the team access to different namespaces by creating a RoleBinding in those namespaces to that SA?

**Comment by stefanprodan** [comment]
`flux create tenant` accepts multiple namespaces and does create an account per namespace.

**Comment by nuriel77** [comment]
Thank you
