### ISSUE TITLE
Default service account forbidden to patch namespaces

### ISSUE THREAD

**Issue by raymondchen625** [fluxcd/flux2-multi-tenancy#69]
Follow the readme with my local Kind cluster, it fails with error messages:

`tenants		False	False	Namespace/apps dry-run failed, reason: Forbidden, error: namespaces "apps" is forbidden: User "system:serviceaccount:flux-system:default" cannot patch resource "namespaces" in API group "" in the namespace "apps"`

A workaround is running this to create a clusterrolebinding upon seeing the error:

```
    kubectl create clusterrolebinding --serviceaccount="flux-system:default" -n flux-system --clusterrole="cluster-admin" my-flux-crb
```

**Comment by stefanprodan** [comment]
Flux doesn’t uses the default account, instead we patch it like this https://github.com/fluxcd/flux2-multi-tenancy/blob/main/clusters/staging/flux-system/kustomization.yaml#L24

**Comment by raymondchen625** [comment]
> Flux doesn’t uses the default account, instead we patch it like this https://github.com/fluxcd/flux2-multi-tenancy/blob/main/clusters/staging/flux-system/kustomization.yaml#L24

Yeah, I would assume when flux applies the manifest it would use the `kustomize-controller` service account. But the error message apparently shows the "default" service account is being used. This only happens when I fork the `flux2-multi-tenancy` and follows the steps in readme. If I use the steps in flux2, everything is fine.

**Comment by stefanprodan** [comment]
Forking this repo and running bootstrap for staging should work file, since we set the SA to kustomize-controller. I’m really surprised it doesn’t work for you.

**Comment by venkatesh-mb** [comment]
Even i have the same issue.  my situation where fleet repository and tenant repository. All applications we want to deploy with tenant repository and want to use fleet repo to manage resource management but it's failing with same. How can we overcome this error.

**Comment by stefanprodan** [comment]
This was fixed here https://github.com/fluxcd/flux2-multi-tenancy/pull/72

@venkatesh-mb are you using the latest main revision from this repo? Can you post here the error message and the Flux Kustomization that you are using?

**Comment by venkatesh-mb** [comment]
This is the error we get when we try to apply some objects in other namespaces.
```
reason: Forbidden, error: resourcequotas \"compute-resources\" is forbidden: User \"system:serviceaccount:flux-system:default\" cannot patch resource \"resourcequotas\" in API group \"\" in the namespace \"team-dev\"\n"}
```
If we remove this patch https://github.com/fluxcd/flux2-multi-tenancy/blob/main/clusters/staging/flux-system/kustomization.yaml#L24 then it's working without any issues.

**Comment by stefanprodan** [comment]
Can you please post the whole log line not just some parts of it? Also post here `flux version`

**Comment by venkatesh-mb** [comment]
```
{"level":"error","ts":"2022-06-02T08:42:52.927Z","logger":"controller.kustomization","msg":"Reconciliation failed after 781.929266ms,next try in 1m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"resource","namespace":"flux-system","revision":"master/a741ab66857a7afefdf6a93bc47cb059bfe8cee7","error":"ResourceQuota/dev/compute-resources dry-run failed, reason: Forbidden, error: resourcequotas \"compute-resources\" is forbidden: User \"system:serviceaccount:flux-system:default\" cannot patch resource \"resourcequotas\" in API group \"\" in the namespace \"dev\"\n"}
```
this is the complete error log and we use # Flux Version: v0.30.2

**Comment by stefanprodan** [comment]
Post here `flux export ks resource`

**Comment by venkatesh-mb** [comment]
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: resource
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./tenants/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

**Comment by stefanprodan** [comment]
@venkatesh-mb all Flux Kustomization in the `flux-system` namespace must set `serviceAccountName: kustomize-controller`.
