### ISSUE TITLE
Single base repository for multiple tenants

### ISSUE THREAD

**Issue by venkatesh-mb** [fluxcd/flux2-multi-tenancy#74]
Is it possible to have single base repository for multiple tenants?
Where i have multiple tenants and they want to refer same base manifest files from one repository, having central base repository and refer in all tenant repository's.

**Comment by stefanprodan** [comment]
Yes, in the tenant GitRepository you can include other repos, docs here: https://fluxcd.io/docs/components/source/gitrepositories/#include

**Comment by venkatesh-mb** [comment]
thanks @stefanprodan . 

    - repository:
        name: other-repository
Does it means it's just a name of the repository? when we try updating it with repository from same organization it's failing  **could not get resource for include 'gitops-admin': GitRepository.source.toolkit.fluxcd.io "gitops-admin" not found**

Where i have added gitops-admin is the repo where we want to keep our base files and from there we want to refer in other tenant repositories.

**Comment by venkatesh-mb** [comment]
I got from here, how it's used https://github.com/fluxcd/source-controller/blob/main/docs/spec/v1beta1/gitrepositories.md

**Comment by venkatesh-mb** [comment]
Does it copies the files from Base repo to tenant repo? or is it refer in tenant repo from base repo?
How can we refer these files in my tenant kustimasation file from base repo location files?

I tried like this, 

spec:
  interval: 1m0s
  include:
    - repository:
        name: base-repo
      fromPath: /base-files/abc
      toPath: /base/abc

Here we want to copy or refer files from base repo to tenant repo

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
resources:
  - /base-files/abc
patchesStrategicMerge:
  - path.yaml

  accumulating resources: accumulation err='accumulating resources from 
  '/base-files/abc': fs-security-constraint read /base-files/abc: path 
  '/base-files/abc' is not in or below '/tmp/kustomization-277909443'':
   new root '/base-files/abc' cannot be absolute"}

**Comment by venkatesh-mb** [comment]
Manifests from GitRepository file.

In this file we are trying to copy or refer files from base-files/abc path which is in base repo to /base/abc in tenant repo


```spec:
  interval: 1m0s
  include:
    - repository:
        name: base-repo
      fromPath: /base-files/abc
      toPath: /base/abc```

```apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
resources:
  - /base/abc
patchesStrategicMerge:
  - path.yaml```
