### ISSUE TITLE
What are plain Kubernetes manifests in context of autogeneration of kustomization.yaml?

### ISSUE THREAD

**Issue by ar-qun** [fluxcd/flux2-multi-tenancy#75]
Hello everyone,

I wanted to understand what does `plain Kubernetes manifests` mean in

> Note that the source should contain the kustomization.yaml and all the Kubernetes manifests and configuration files referenced in the kustomization.yaml. If your Git repository or S3 bucket contains only plain manifests, then a kustomization.yaml will be automatically generated.

Would a `HelmRelease` be considered a plain manifest in this case? If so than non-plain manifests would be Helm Charts and kustomization patches?

Thanks!

**Comment by stefanprodan** [comment]
Plain manifests are those that can be applied with kubectl, so no templating (helm charts) nor kustomize patches.
