### ISSUE TITLE
Flux v2: Notifications controller

### ISSUE THREAD

**Issue by venkatesh-mb** [fluxcd/flux2-multi-tenancy#76]
We understand that this time flux support only  slack, msteams, discord, rocket, googlechat, webex, sentry or generic.. Any idea when we will be onboarding mattermost to this list?

**Comment by stefanprodan** [comment]
You can use the Slack provider as it seems that Mattermost is compatible with Slack formatting: https://docs.mattermost.com/developer/webhooks-incoming.html

PS. This is not the right repository to ask such things, please use https://github.com/fluxcd/notification-controller
