### ISSUE TITLE
Instructions in README does not seem to work

### ISSUE THREAD

**Issue by torpare** [fluxcd/flux2-multi-tenancy#91]
I've tried to follow the steps in the README in order to create a flux-managed k8s cluster.

Sadly, somethings goes south after a few steps. Here's what I've tried:

(Note that I'm using Gitlab rather than Github)

Creating cluster in Kind and cloning tutorital repo:
```
kind create cluster --name stagingcluster
git clone https://github.com/fluxcd/flux2-multi-tenancy
cd ~/flux2-multi-tenancy
```
Env vars
```
export GITLAB_TOKEN=<omitted>
export GITLAB_GROUP=<omitted>
export GITLAB_REPO=multitenantflux
```
Boostrapping Flux
```
flux bootstrap gitlab \
    --context=kind-stagingcluster \
    --owner=${GITLAB_GROUP} \
    --repository=${GITLAB_REPO} \
    --branch=main \
    --path=./clusters/staging
```
Verifying that Flux has created repo in Gitlab
```
cd ~
git clone git@gitlab.com:${GITLAB_GROUP}/${GITLAB_REPO}.git
cd ~/multitenantflux
```

Check that files are in place:
```
> tree

.
└── clusters
    └── staging
        └── flux-system
            ├── gotk-components.yaml
            ├── gotk-sync.yaml
            └── kustomization.yaml
```
**This is where things seems to look out-of-place:**
```
> flux get kustomizations --watch
NAME            REVISION        SUSPENDED       READY   MESSAGE
flux-system     main/a91673b    False           True    Applied revision: main/a91673b
```
(here i expected to see kyverno, kyverno-policies and tenants  but no luck)
```
> flux -n apps get sources git
✗ no GitRepository objects found in apps namespace
```
(here i expected a tenant dev-team to be listed)
anyone knows? :slightly_smiling_face: :pray:

**Comment by kingdonb** [comment]
Did you push up your fork of flux2-multi-tenancy to the new repo in GitLab before beginning this attempt?

The directions here assume that you will have forked this repo, (which you can't have done on GitLab.)

It's assumed that you'll bootstrap into the already existing path ./clusters/staging and that all references from there to resources in the rest of the repo are intact. You might have better luck if you try the guide without trying to convert it to GitLab at first. This guide is for learning Flux, you can make a new repo on GitLab later and replicate the examples there, but support issues that appear to be related to someone's off-the-beaten-path replay of these guides are difficult to triage.

In general, when you're troubleshooting or learning at first, it's much better to use a public repo, that way we can also point out specific mistakes without guessing what caused the issue. Hope this helps!

**Comment by borqq** [comment]
Thanks @kingdonb, I tried to fork the repo and now everything works as intended :) 

I suppose the fork-step is obvious to most readers, but nevertheless i feel like it should be explicitly expressed in the documentation.

The fact the `flux bootstrap` actually creates a new repo for you, if you don't point to an existing repo, contributed to my confusion.

**Comment by torpare** [comment]
Thanks @kingdonb, I tried to fork the repo and now everything works as intended :)

I suppose the fork-step is obvious to most readers, but nevertheless i feel like it should be explicitly expressed in the documentation.

The fact the flux bootstrap actually creates a new repo for you, if you don't point to an existing repo, contributed to my confusion.
